### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by DHW-Master** [Mehrdad-Noori/CAGNet#1]
I can't download the vgg-16 pre-trained model. Could you  provide a new link or send it to my email? Thank you !
My email is donghongwenliran@gmail.com

**Comment by Mehrdad-Noori** [comment]
Thank very much for your interest. 
The weights are uploaded on Google Drive as mentioned in readme. My colleagues and I checked it and we managed to download it without any problem. However, if it is not possible for you to download it from Google Drive, could you please suggest an alternative way to me for uploading the weights?
