### ISSUE TITLE
Does this network work for polyps?

### ISSUE THREAD

**Issue by ruirui-xia** [Mehrdad-Noori/CAGNet#4]
Hello, I'm very interested in your paper.
I have reproduced your code, but the output of the trained network parameters in the test is all black, with no effect of segmentation. I tried the network parameters after your training, and they have results.
Now I do not know what is the problem, If you have time, please tell me.
Thank you!

**Comment by Mehrdad-Noori** [comment]
Thank you for your interest.
Have you trained the model on your dataset or you have just used our pre-trained weights?
