### ISSUE TITLE
the password for Baidu cloud disk 

### ISSUE THREAD

**Issue by LnSCV** [Mehrdad-Noori/CAGNet#5]
Is it convenient for you to tell me the extraction password of Baidu cloud disk！Thank you!

**Comment by Shannon1997** [comment]
+1.  I would be very grateful if you could reply to the Baidu cloud extraction code. Thanks!

**Comment by lixiaotong16** [comment]
+1. I would be very grateful if you could reply to the Baidu cloud extraction code of CAGNet-R model. Thanks!

**Comment by Mehrdad-Noori** [comment]
Sorry for the inconvenience. The README is updated with the Baidu extraction codes. Thanks for bringing it to our attention.

**Comment by lixiaotong16** [comment]
Thank you very much for replying to this issue. But the Baidu extraction codes you provided does not correspond to the link. And the Google Drive link is also invalid. Could you check it out? Thanks!

**Comment by Mehrdad-Noori** [comment]
I have updated them. Would you please check the Baidu extraction codes again and let me know whether they work?
I am going to fix the problem with the google drive links.

**Comment by lixiaotong16** [comment]
Sorry, the extraction codes are still incorrect. Looking forward to the restoration of the Google drive links. Thank you very much again！

**Comment by Mehrdad-Noori** [comment]
I am so sorry. Could you please check the Baidu links again? I hope they work this time.

**Comment by lixiaotong16** [comment]
They all work! Thank you very much!
